import fs from 'node:fs/promises'
import path from 'node:path'
import assert from 'node:assert/strict'
import {pathToFileURL} from 'node:url'
const entry='.list-design-test-entry.js', filename='.list-design-test.html'
const source=`
import {createApp,h,ref,nextTick} from 'vue';
import ElementPlus from 'element-plus';import 'element-plus/dist/index.css';
import ModelTable from '/src/views/business/formModel/ModelTable.vue';
import ListDesigner from '/src/views/business/formModel/ListDesigner.vue';
import {syncFields} from '/src/views/business/formModel/fields.js';
import request from '/src/utils/request.js';import {getModelRecords} from '/src/api/business/formModel.js';
import {normalizeListConfig,previewQuery} from '/src/views/business/formModel/listConfig.js';
const fields=ref(syncFields([{type:'inputNumber',field:'amount',title:'金额'},{type:'input',field:'title',title:'标题'},{type:'switch',field:'active',title:'启用'},{type:'input',field:'hidden',title:'隐藏字段'}]));
fields.value.forEach(f=>f.sortable=true);fields.value[1].width=220;fields.value[3].visible=false;
const config=ref(normalizeListConfig({},fields.value));config.value.table.defaultWidth=140;config.value.table.pageSize=10;
const records=Array.from({length:25},(_,i)=>({id:100+i,values:{amount:i,title:'Title '+i,active:!!(i%2),hidden:'Secret'}}));
window.testQueryApi=async()=>{const previous=request.defaults.adapter;const seen=[];request.defaults.adapter=async config=>{seen.push({url:config.url,method:config.method,data:JSON.parse(config.data)});return {config,request:{responseType:'json'},data:{code:200,data:{rows:[],total:0,pageNum:1,pageSize:10}},status:200,statusText:'OK',headers:{}}};try{const q={pageNum:1,pageSize:10,conditions:[],relation:'and',sort:null};await getModelRecords(123,q);await getModelRecords(123,q);return seen}finally{request.defaults.adapter=previous}};
const calls=[], list=ref(), designer=ref(false);
window.harness={fields,config,records,calls,list,designer,edits:[],creates:0,delay:0};
const loader=async q=>{calls.push(JSON.parse(JSON.stringify(q)));let result=previewQuery(records,fields.value,q);const delay=window.harness.delay;await new Promise(r=>setTimeout(r,delay));return result};
createApp({setup(){return()=>designer.value?h(ListDesigner,{fields:fields.value,config:config.value}):h(ModelTable,{ref:list,fields:fields.value,config:config.value,loader,onEdit:r=>window.harness.edits.push(r),onCreate:()=>window.harness.creates++})}}).use(ElementPlus).mount('#test');
`
await fs.writeFile(entry,source)
await fs.writeFile(filename,'<!doctype html><html><meta charset="UTF-8"><body style="padding:20px;font-family:Arial,Microsoft YaHei,sans-serif"><div id="test"></div><script type="module" src="/'+entry+'"></script></body></html>')
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE || path.join(process.env.TEMP,'ruoyi-toolbar-browser/node_modules/playwright-core/index.mjs')))
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true})
const page=await browser.newPage({viewport:{width:1360,height:1100}})
const errors=[];page.on('pageerror',error=>errors.push(error.message))
const calls=()=>page.evaluate(()=>window.harness.calls)
const result=()=>page.locator('.result-heading').innerText()
async function idle(){await page.waitForFunction(()=>window.harness?.calls.length>0);await page.locator('.el-loading-mask:visible').waitFor({state:'hidden'});await page.waitForTimeout(100)}
try {
 await page.goto((process.env.RUOYI_FRONTEND_URL||'http://127.0.0.1')+'/'+filename)
 await idle()
 assert.match(await result(),/共 25 条/)
 assert.equal(await page.getByRole('button',{name:'修改',exact:true}).isDisabled(),true)
 await page.getByRole('button',{name:'新增',exact:true}).click()
 assert.equal(await page.evaluate(()=>window.harness.creates),1)
 const apiCalls=await page.evaluate(()=>window.testQueryApi())
 assert.equal(apiCalls.length,2);assert.equal(apiCalls[0].method,'post');assert.match(apiCalls[0].url,/records\/query$/);assert.equal(apiCalls[0].data.pageSize,10)
 console.log('PASS: real Vue/Element/VTable mounted; toolbar, query API payload, immediate refresh not blocked as duplicate POST')
 await page.getByRole('button',{name:'添加条件',exact:false}).click()
 await page.locator('.condition-row .el-input-number input').fill('0')
 await page.getByRole('button',{name:'查询',exact:true}).click();await idle()
 assert.match(await result(),/共 1 条/)
 assert.deepEqual((await calls()).at(-1).conditions,[{field:'amount',operator:'eq',value:0}])
 await page.locator('.condition-row .el-input-number input').fill('2')
 await page.getByRole('button',{name:'刷新',exact:true}).click();await idle()
 assert.equal((await calls()).at(-1).conditions[0].value,0)
 console.log('PASS: zero query; draft edits do not affect refresh of submitted conditions')
 await page.getByRole('button',{name:'重置',exact:true}).click();await idle()
 assert.equal((await calls()).at(-1).conditions.length,0)
 // Actual canvas header interaction must request server sorting rather than rearranging the current page.
 const box=await page.locator('.model-table').boundingBox()
 await page.mouse.click(box.x+59,box.y+20);await idle()
 assert.deepEqual((await calls()).at(-1).sort,{field:'amount',order:'asc'})
 await page.locator('.el-pagination .btn-next').click();await idle()
 assert.equal((await calls()).at(-1).pageNum,2)
 await page.mouse.click(box.x+60,box.y+60)
 assert.equal(await page.getByRole('button',{name:'修改',exact:true}).isEnabled(),true)
 await page.getByRole('button',{name:'修改',exact:true}).click()
 assert.equal(await page.evaluate(()=>window.harness.edits.at(-1).id),110)
 await page.mouse.dblclick(box.x+60,box.y+100)
 await page.waitForFunction(()=>window.harness.edits.length===2)
 assert.equal(await page.evaluate(()=>window.harness.edits.at(-1).id),111)
 await page.mouse.click(box.x+59,box.y+20);await idle()
 assert.deepEqual((await calls()).at(-1).sort,{field:'amount',order:'desc'})
 await page.mouse.click(box.x+59,box.y+20);await idle()
 assert.equal((await calls()).at(-1).sort,null)
 console.log('PASS: canvas asc/desc/clear sorting; cross-page ID selection and double-click editing')
 await page.getByRole('button',{name:'刷新',exact:true}).click();await idle()
 assert.equal(await page.getByRole('button',{name:'修改',exact:true}).isDisabled(),true)
 // Correct the active page after records are removed on the server.
 await page.evaluate(async()=>{window.harness.records.splice(1);await window.harness.list.value.reload()});await idle()
 assert.match(await result(),/共 1 条/)
 assert.equal(await page.locator('.el-pager .is-active').innerText(),'1')
 // Older in-flight response must not overwrite a newer result.
 await page.evaluate(async()=>{const h=window.harness;h.delay=250;const old=h.list.value.reload();h.records.push({id:999,values:{amount:99,title:'New'}});h.delay=0;await h.list.value.reload();await old});await idle()
 assert.match(await result(),/共 2 条/)
 console.log('PASS: refresh clears selection; overflow page corrected; stale response ignored')
 await page.evaluate(()=>{const h=window.harness;h.config.value.buttons.find(b=>b.key==='edit').visible=false;h.config.value.buttons.find(b=>b.key==='refresh').label='重新加载'});await idle()
 assert.equal(await page.getByRole('button',{name:'修改',exact:true}).count(),0)
 assert.equal(await page.getByRole('button',{name:'重新加载',exact:true}).count(),1)
 const editCount=await page.evaluate(()=>window.harness.edits.length)
 await page.mouse.dblclick(box.x+60,box.y+60)
 assert.equal(await page.evaluate(()=>window.harness.edits.length),editCount)
 await page.evaluate(()=>{const h=window.harness;h.config.value.buttons.find(b=>b.key==='edit').visible=true;h.config.value.buttons.find(b=>b.key==='refresh').label='刷新';h.config.value.filters.defaults=[{field:'amount',operator:'gte'}];h.designer.value=true})
 await page.getByRole('tab',{name:'视图配置',exact:true}).waitFor()
 await page.locator('.list-canvas .model-table canvas').first().waitFor()
 assert.equal(await page.locator('.list-canvas .list-filters').isVisible(),false)
 const state=()=>page.evaluate(()=>JSON.stringify({fields:window.harness.fields.value,config:window.harness.config.value}))
 const stateBeforePicker=await state()
 await page.getByRole('button',{name:'设置查询条件',exact:true}).click()
 let dialog=page.getByRole('dialog',{name:'设置查询条件',exact:true})
 await dialog.getByRole('checkbox',{name:'隐藏字段',exact:true}).locator('..').click()
 assert.equal(await state(),stateBeforePicker,'Selection is staged until confirmed')
 await dialog.getByRole('button',{name:'取消',exact:true}).click()
 await dialog.waitFor({state:'hidden'})
 assert.equal(await state(),stateBeforePicker,'Cancel must not mutate configuration')
 await page.getByRole('button',{name:'设置查询条件',exact:true}).click()
 dialog=page.getByRole('dialog',{name:'设置查询条件',exact:true})
 await dialog.getByPlaceholder('搜索字段',{exact:true}).fill('hidden')
 await dialog.getByRole('checkbox',{name:'全选搜索结果',exact:true}).locator('..').click()
 await dialog.getByPlaceholder('搜索字段',{exact:true}).fill('')
 const hidden=dialog.locator('.selected-field[data-field="hidden"]')
 await hidden.hover();await hidden.getByRole('button',{name:'上移隐藏字段',exact:true}).click()
 assert.equal(await dialog.locator('.selected-field').first().getAttribute('data-field'),'hidden')
 // Drag the original amount condition above the hidden field; its operator must survive.
 const from=await dialog.locator('.selected-field[data-field="amount"] .drag-handle').boundingBox()
 const to=await hidden.boundingBox()
 await page.mouse.move(from.x+from.width/2,from.y+from.height/2)
 await page.mouse.down();await page.mouse.move(from.x+from.width/2,from.y+from.height/2-8,{steps:3});await page.waitForTimeout(150)
 await page.mouse.move(to.x+12,to.y+3,{steps:12});await page.waitForTimeout(200);await page.mouse.up()
 await page.waitForFunction(()=>document.querySelector('.list-field-picker .selected-field')?.dataset.field==='amount')
 await dialog.getByRole('button',{name:'确定',exact:true}).click();await dialog.waitFor({state:'hidden'})
 assert.deepEqual(await page.evaluate(()=>window.harness.config.value.filters.defaults),[{field:'amount',operator:'gte'},{field:'hidden',operator:'contains'}])
 console.log('PASS: reference two-pane picker, staged cancel/confirm, hidden fields, search/select-all, arrow and real drag ordering')
 await page.getByRole('button',{name:'设置查询条件',exact:true}).click()
 dialog=page.getByRole('dialog',{name:'设置查询条件',exact:true})
 await dialog.getByPlaceholder('搜索已选字段',{exact:true}).fill('hidden')
 await dialog.getByRole('button',{name:'移除隐藏字段',exact:true}).click()
 await dialog.getByRole('button',{name:'确定',exact:true}).click();await dialog.waitFor({state:'hidden'})
 assert.equal(await page.evaluate(()=>window.harness.config.value.filters.defaults.length),1)
 await page.locator('.query-settings .side-field').first().hover()
 await page.getByRole('button',{name:'设置查询条件1',exact:true}).click()
 await page.getByRole('button',{name:'添加同字段条件',exact:true}).click()
 await page.locator('.canvas-heading strong').click()
 assert.equal(await page.evaluate(()=>window.harness.config.value.filters.defaults.length),2)
 await page.getByRole('button',{name:'设置查询条件',exact:true}).click()
 dialog=page.getByRole('dialog',{name:'设置查询条件',exact:true})
 assert.equal(await dialog.locator('.selected-field').count(),2,'Existing repeated conditions must not collapse')
 await dialog.getByRole('button',{name:'确定',exact:true}).click();await dialog.waitFor({state:'hidden'})
 assert.deepEqual(await page.evaluate(()=>window.harness.config.value.filters.defaults.map(c=>c.operator)),['gte','gte'])
 await page.getByRole('button',{name:'设置展示字段',exact:true}).click()
 dialog=page.getByRole('dialog',{name:'设置展示字段',exact:true})
 await dialog.getByRole('button',{name:'清空',exact:true}).click()
 await dialog.getByRole('checkbox',{name:'隐藏字段',exact:true}).locator('..').click()
 await dialog.getByRole('checkbox',{name:'标题',exact:true}).locator('..').click()
 await dialog.getByRole('button',{name:'确定',exact:true}).click();await dialog.waitFor({state:'hidden'})
 assert.deepEqual(await page.evaluate(()=>window.harness.fields.value.filter(f=>f.visible).sort((a,b)=>a.order-b.order).map(f=>f.field)),['hidden','title'])
 await page.locator('.column-settings').getByRole('button',{name:'标题',exact:true}).click()
 await page.locator('.property-line .el-input-number input').first().fill('180')
 await page.locator('.property-line .el-input-number input').nth(1).fill('')
 await page.locator('.settings-title').filter({hasText:'列表属性'}).click()
 assert.equal(await page.evaluate(()=>window.harness.config.value.table.defaultWidth),180)
 assert.equal(await page.evaluate(()=>window.harness.fields.value[1].width == null),true)
 await page.getByRole('tab',{name:'视图配置',exact:true}).click()
 await page.getByRole('button',{name:'设置排序字段',exact:true}).click()
 dialog=page.getByRole('dialog',{name:'设置排序字段',exact:true})
 await dialog.getByRole('checkbox',{name:'启用',exact:true}).locator('..').click()
 await dialog.getByRole('checkbox',{name:'金额',exact:true}).locator('..').click()
 assert.equal(await dialog.locator('.selected-field').count(),1)
 await dialog.getByRole('button',{name:'确定',exact:true}).click();await dialog.waitFor({state:'hidden'})
 assert.deepEqual(await page.evaluate(()=>window.harness.config.value.table.defaultSort),{field:'amount',order:'asc'})
 await page.getByRole('tab',{name:'视图属性',exact:true}).click()
 await page.locator('.settings-body>.el-select').click()
 await page.getByRole('option',{name:'金额 (amount)',exact:true}).click()
 await page.getByRole('switch',{name:'允许当前字段排序',exact:true}).locator('..').click()
 assert.equal(await page.evaluate(()=>window.harness.config.value.table.defaultSort),null)
 await page.getByRole('tab',{name:'视图配置',exact:true}).click()
 await page.locator('.action-settings .side-field').first().hover()
 await page.getByRole('button',{name:'设置新增按钮',exact:true}).click()
 await page.locator('.button-properties input').first().fill('添加记录')
 await page.locator('.button-properties .el-input-number input').fill('3')
 await page.locator('.canvas-heading strong').click()
 assert.equal(await page.evaluate(()=>window.harness.config.value.buttons[0].label),'添加记录')
 assert.equal(await page.evaluate(()=>window.harness.config.value.buttons[0].order),3)
 await page.getByRole('checkbox',{name:'显示新增按钮',exact:true}).locator('..').click()
 assert.equal(await page.locator('.list-canvas').getByRole('button',{name:'添加记录',exact:true}).count(),0)
 await page.getByRole('checkbox',{name:'显示新增按钮',exact:true}).locator('..').click()
 const businessCalls=(await calls()).length
 await page.locator('.list-canvas').getByRole('button',{name:'添加记录',exact:true}).click()
 assert.equal(await page.evaluate(()=>window.harness.creates),1)
 assert.equal((await calls()).length,businessCalls,'Canvas is mock-only')
 await page.locator('.canvas-tools').getByRole('button',{name:'筛选',exact:true}).click()
 assert.equal(await page.locator('.list-canvas .list-filters').isVisible(),true)
 await page.locator('.canvas-tools').getByRole('button',{name:'筛选',exact:true}).click()
 await page.locator('.el-message').waitFor({state:'hidden'})
 console.log('PASS: repeated filters, display order, column properties, single-field sort, button settings and mock isolation')
 // A larger in-browser-only fixture demonstrates the reference layout, not real business records.
 await page.evaluate(()=>{const h=window.harness;Object.assign(h.config.value.buttons[0],{label:'新增',order:1});h.config.value.table.defaultWidth=160;h.fields.value.forEach((f,i)=>{f.visible=i<3;f.order=i+1;f.sortable=true});h.fields.value[1].width=220;
 const extra=[['code','单据号'],['category','变更类别'],['effective','生效日期'],['owner','负责人'],['reason','变更原因'],['remark','备注'],['department','所属部门'],['status','审批状态']];
 extra.forEach(([field,title],i)=>h.fields.value.push({field,title,type:'input',valueType:'text',visible:i<2,sortable:true,order:i+5,options:[]}));h.config.value.filters.defaults=[{field:'effective',operator:'contains'},{field:'code',operator:'contains'},{field:'owner',operator:'contains'}]})
 await page.setViewportSize({width:1440,height:960});await page.mouse.move(5,5);await page.waitForTimeout(200)
 await page.locator('.list-designer').screenshot({path:'scripts/list-design-preview.png'})
 await page.getByRole('button',{name:'设置查询条件',exact:true}).click()
 dialog=page.getByRole('dialog',{name:'设置查询条件',exact:true});await dialog.waitFor();await page.waitForTimeout(350)
 await page.screenshot({path:'scripts/list-design-field-picker.png',fullPage:true})
 await page.setViewportSize({width:600,height:900});await page.waitForTimeout(200)
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Picker must fit narrow screens')
 await dialog.getByRole('button',{name:'取消',exact:true}).click();await dialog.waitFor({state:'hidden'})
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Designer must fit narrow screens')
 console.log('PASS: desktop reference screenshots and responsive designer/picker')
 assert.deepEqual(errors,[])
 console.log('PASS: browser regression; no page errors')
} catch (failure) { console.log('PAGE ERRORS',JSON.stringify(errors));await page.screenshot({path:path.join(process.env.TEMP || '.', 'ruoyi-list-design-debug.png'),fullPage:true});throw failure } finally {await browser.close();await fs.rm(entry,{force:true});await fs.rm(filename,{force:true})}
